name: SonarCloud Analysis
on:
  push:
    branches: [ main, Optimization ]
  pull_request:
    branches: [ main ]

jobs:
  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: SonarCloud Scan
      uses: SonarSource/sonarqube-scan-action@v6
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.organization=halif32
          -Dsonar.projectKey=halif32_Avidbots
          -Dsonar.branch.name=${{ github.head_ref || github.ref_name }}