name: SonarCloud Analysis
on:
  push:
    branches: [ main, Optimization ]
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened]  # Explicitly state PR events

jobs:
  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: SonarCloud Scan
      uses: SonarSource/sonarqube-scan-action@v6
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Add this for PR decoration
      with:
        args: >
          -Dsonar.organization=halif32
          -Dsonar.projectKey=halif32_Avidbots
          -Dsonar.pullrequest.key=${{ github.event.pull_request.number }}
          -Dsonar.pullrequest.branch=${{ github.head_ref }}
          -Dsonar.pullrequest.base=${{ github.base_ref }}